### ISSUE TITLE
Improve tank steering behaviour

### ISSUE THREAD

**Issue by Derpius** [Blu-x92/lvs_cars#3]
# Context

An issue present in both the legacy simfphys armed and this addon is tanks controlling as if they were regular cars. This means that you must apply gas in order for the vehicle to turn.

# Expected

- When pressing the left or right buttons (or otherwise activating a turn input), then the tank traverses
  - This could be neutral steering for simplicity, or could be made more realistic for the sherman and tiger tanks provided

# Actual

- When activating a turn input, nothing happens
  - You must apply gas in order to turn

**Comment by Blu-x92** [comment]
added in https://github.com/Blu-x92/lvs_cars/commit/9fe9c1499ddc182c5de919853b802137a98f28dc

In your vehicle init.lua add:
ENT.PivotSteerEnable = true -- enables pivot steer
ENT.PivotSteerWheelRPM = 40 -- adjust turn rate (sets wheel target rpm directly)

in your self:AddWheel() line you need to add a wheeltype variable so the code knows which direction to spin the wheel:

local Wheel = self:AddWheel( { ..., ..., wheeltype = LVS.WHEELTYPE_LEFT, pos = Vector(1,2,3), ..., ... } )

wheeltype can be either LVS.WHEELTYPE_LEFT or LVS.WHEELTYPE_RIGHT

see tiger for reference:
https://github.com/Blu-x92/lvs_cars/blob/main/lua/entities/lvs_wheeldrive_dodtiger/sh_tracks.lua

or template:
https://github.com/Blu-x92/lvs_cars/blob/main/lua/entities/lvs_wheeldrive_template/init.lua#L113

I did not add pivot steer to the sherman, because from my research it never came with that feature

**Comment by Derpius** [comment]
While it is impossible to neutral steer in a sherman (and most other WW2 era tanks, including the tiger IIRC), it was still turned by slowing down the track on one side and used two levers for steering.

Regardless of that though, from a gameplay perspective it feels more natural for the tank to traverse when inputting a left or right turn (even if it doesn’t neutral steer, i.e. it can’t turn on the spot).

A great example of this is War Thunder where even in tanks which historically had poor traversal, you can still traverse with only left or right inputs and it will just turn with the smallest radius possible.

**Comment by Blu-x92** [comment]
added ENT.PivotSteerByBrake variable, so we can have both variants now

**Comment by Derpius** [comment]
Amazing, thanks!
